services:
  - type: web
    name: secure-chat
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server/index.js"
    envVars:
      - key: NODE_ENV
        value: production

